name: test-termios
on: [push, pull_request]

jobs:
  term:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./exp/term
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./exp/term/go.mod
          cache: true
          cache-dependency-path: ./exp/term.sum
      # https://go.dev/doc/install/source#environment
      - run: GOOS=aix	GOARCH=ppc64 go build -v ./termios/...
      - run: GOOS=android GOARCH=386 go build -v ./termios/...
      - run: GOOS=android GOARCH=amd64 go build -v ./termios/...
      - run: GOOS=android GOARCH=arm go build -v ./termios/...
      - run: GOOS=android GOARCH=arm64 go build -v ./termios/...
      - run: GOOS=darwin GOARCH=amd64 go build -v ./termios/...
      - run: GOOS=darwin GOARCH=arm64 go build -v ./termios/...
      - run: GOOS=dragonfly GOARCH=amd64 go build -v ./termios/...
      - run: GOOS=freebsd GOARCH=386 go build -v ./termios/...
      - run: GOOS=freebsd GOARCH=amd64 go build -v ./termios/...
      - run: GOOS=freebsd GOARCH=arm go build -v ./termios/...
      - run: GOOS=illumos GOARCH=amd64 go build -v ./termios/...
      - run: GOOS=linux GOARCH=386 go build -v ./termios/...
      - run: GOOS=linux GOARCH=amd64 go build -v ./termios/...
      - run: GOOS=linux GOARCH=arm go build -v ./termios/...
      - run: GOOS=linux GOARCH=arm64 go build -v ./termios/...
      - run: GOOS=linux GOARCH=loong64 go build -v ./termios/...
      - run: GOOS=linux GOARCH=mips go build -v ./termios/...
      - run: GOOS=linux GOARCH=mipsle go build -v ./termios/...
      - run: GOOS=linux GOARCH=mips64 go build -v ./termios/...
      - run: GOOS=linux GOARCH=mips64le go build -v ./termios/...
      - run: GOOS=linux GOARCH=ppc64 go build -v ./termios/...
      - run: GOOS=linux GOARCH=ppc64le go build -v ./termios/...
      - run: GOOS=linux GOARCH=riscv64 go build -v ./termios/...
      - run: GOOS=linux GOARCH=s390x go build -v ./termios/...
      - run: GOOS=netbsd GOARCH=386 go build -v ./termios/...
      - run: GOOS=netbsd GOARCH=amd64 go build -v ./termios/...
      - run: GOOS=netbsd GOARCH=arm go build -v ./termios/...
      - run: GOOS=openbsd GOARCH=386 go build -v ./termios/...
      - run: GOOS=openbsd GOARCH=amd64 go build -v ./termios/...
      - run: GOOS=openbsd GOARCH=arm go build -v ./termios/...
      - run: GOOS=openbsd GOARCH=arm64 go build -v ./termios/...
      - run: GOOS=plan9 GOARCH=386 go build -v ./termios/...
      - run: GOOS=plan9 GOARCH=amd64 go build -v ./termios/...
      - run: GOOS=plan9 GOARCH=arm go build -v ./termios/...
      - run: GOOS=solaris GOARCH=amd64 go build -v ./termios/...

      # unsupported
      # - run: GOOS=ios GOARCH=arm64 go build -v ./termios/...
      # - run: GOOS=js GOARCH=wasm go build -v ./termios/...
      # - run: GOOS=wasip1 GOARCH=wasm go build -v ./termios/...
      # - run: GOOS=windows GOARCH=386 go build -v ./termios/...
      # - run: GOOS=windows GOARCH=amd64 go build -v ./termios/...
      # - run: GOOS=windows GOARCH=arm go build -v ./termios/...
      # - run: GOOS=windows GOARCH=arm64 go build -v ./termios/...
